from quay.io/keycloak/keycloak:20.0
COPY themes/mantiser /opt/keycloak/themes/mantiser
COPY themes/samma    /opt/keycloak/themes/samma
COPY themes/ollebo    /opt/keycloak/themes/ollebo
#ENTRYPOINT ["/opt/keycloak/bin/kc.sh start"]
